const countriesInAfrica = {
  DZ: "Algeria",
  AO: "Angola",
  BJ: "Benin",
  BW: "Botswana",
  BF: "Burkina Faso",
  BI: "Burundi",
  CM: "Cameroon",
  CV: "Cape Verde",
  CF: "Central African Republic",
  TD: "Chad",
  KM: "Comoros",
  DJ: "Djibouti",
  EG: "Egypt",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  ET: "Ethiopia",
  GA: "Gabon",
  GM: "Gambia",
  GH: "Ghana",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  CI: "Ivory Coast",
  KE: "Kenya",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libya",
  MG: "Madagascar",
  MW: "Malawi",
  ML: "Mali",
  MR: "Mauritania",
  MU: "Mauritius",
  MA: "Morocco",
  MZ: "Mozambique",
  NA: "Namibia",
  NE: "Niger",
  NG: "Nigeria",
  CG: "Republic of the Congo",
  CD: "Democratic Republic of the Congo",
  RE: "Réunion",
  RW: "Rwanda",
  SH: "Saint Helena",
  ST: "São Tomé and Príncipe",
  SN: "Senegal",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SO: "Somalia",
  ZA: "South Africa",
  SS: "South Sudan",
  SD: "Sudan",
  SZ: "Eswatini",
  TZ: "Tanzania",
  TG: "Togo",
  TN: "Tunisia",
  UG: "Uganda",
  EH: "Western Sahara",
  ZM: "Zambia",
  ZW: "Zimbabwe",
};

export default countriesInAfrica