const countriesInNorthAmerica = {
  AI: "Anguilla",
  AG: "Antigua and Barbuda",
  AW: "Aruba",
  BS: "Bahamas",
  BB: "Barbados",
  BZ: "Belize",
  BM: "Bermuda",
  VG: "British Virgin Islands",
  CA: "Canada",
  KY: "Cayman Islands",
  CR: "Costa Rica",
  CU: "Cuba",
  DM: "Dominica",
  DO: "Dominican Republic",
  SV: "El Salvador",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GT: "Guatemala",
  HT: "Haiti",
  HN: "Honduras",
  JM: "Jamaica",
  MQ: "Martinique",
  MX: "Mexico",
  NI: "Nicaragua",
  PA: "Panama",
  PR: "Puerto Rico",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  MF: "Saint Martin",
  VC: "Saint Vincent and the Grenadines",
  TT: "Trinidad and Tobago",
  VI: "U.S. Virgin Islands",
  US: "United States",
};

export default countriesInNorthAmerica