const countriesInOceeania = {
  AS: "American Samoa",
  AU: "Australia",
  CK: "Cook Islands",
  FJ: "Fiji",
  PF: "French Polynesia",
  GU: "Guam",
  KI: "Kiribati",
  MH: "Marshall Islands",
  FM: "Micronesia",
  NR: "Nauru",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NU: "Niue",
  NF: "Norfolk Island",
  PW: "Palau",
  PG: "Papua New Guinea",
  WS: "Samoa",
  SB: "Solomon Islands",
  TK: "Tokelau",
  TO: "Tonga",
  TV: "Tuvalu",
  VU: "Vanuatu",
};

export default countriesInOceeania;
